### ISSUE TITLE
Docker image deploys tracker

### ISSUE THREAD

**Issue by marvinscham** [Alyetama/Rembg-Online#2]
The Streamlit config does not work for the Docker image, meaning that along with the other options `gatherUsageStats = false` is not applied. This results in the deployment of Streamlit's standard tracking script.

![image](https://github.com/Alyetama/Rembg-Online/assets/67930021/909f1a4d-a3e8-4914-a052-c1477bce07ec)

**Comment by Alyetama** [comment]
Are you using `docker-compose` or just `docker run`?

**Comment by marvinscham** [comment]
Sorry, false alarm.
I tried using the `docker-compose` on the freshly downloaded repo but missed the dotfiles including the `.streamlit` folder when unpacking. It works as intended now.
